version: '3'
services:
  yep-bot:
    image: aygreyg/yep-bot:1.1
    environment:

      ###########################################################
      #                       Must haves                        #
      ###########################################################
      TOKEN: token
      CLIENTID: clientid
      PREFIX: "?"

      ###########################################################
      #   Optional, uncomment and change them in order to use   #
      ###########################################################
      # MCIP: ip
      # MCPORT: port
      # PROGRESSBAR_EMOTE: emote

    volumes:
      - db-data:/app/data
volumes:
  db-data:
